version: '3.9'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - $PWD/data:/freqtrade/user_data
      - $PWD/strategies:/freqtrade/user_data/strategies
      - $PWD/entrypoint.sh:/freqtrade/entrypoint.sh
    ports:
      - 8080:8080
    entrypoint: ./entrypoint.sh

